twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/custom_types.html.twig' #template de formulaire pour le widget captcha
    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%' #clée captcha

when@test:
    twig:
        strict_variables: true
